In [81]:
import pandas as pd
import numpy as np

In [82]:
df=pd.read_csv('covid_toy.csv')

In [83]:
df

age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [84]:
df.isnull().sum()

# this function will tell that how much number of null values are there in every columns

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [85]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.drop('has_covid',axis=1),df['has_covid'],test_size=0.2,random_state=0)

In [86]:
X_train

age  gender  fever   cough       city
43   22  Female   99.0    Mild  Bangalore
62   56  Female  104.0  Strong  Bangalore
3    31  Female   98.0    Mild    Kolkata
71   75  Female  104.0  Strong      Delhi
45   72    Male   99.0    Mild  Bangalore
..  ...     ...    ...     ...        ...
96   51  Female  101.0  Strong    Kolkata
67   65    Male   99.0    Mild  Bangalore
64   42    Male  104.0    Mild     Mumbai
47   18  Female  104.0    Mild  Bangalore
44   20    Male  102.0  Strong      Delhi

[80 rows x 5 columns]

# 1. Simple Way to do

In [87]:
from sklearn.impute import SimpleImputer

In [88]:
# as in the column of fever there are 10 rows are null, so to fill that we have to use simple imputer

si = SimpleImputer()
X_train_fever= si.fit_transform(X_train[['fever']])


# also fill test data of fever column

X_test_fever=si.fit_transform(X_test[['fever']])

In [89]:
X_train_fever

array([[ 99.        ],
       [104.        ],
       [ 98.        ],
       [104.        ],
       [ 99.        ],
       [ 99.        ],
       [101.        ],
       [ 98.        ],
       [ 98.        ],
       [100.        ],
       [102.        ],
       [ 99.        ],
       [ 99.        ],
       [104.        ],
       [100.        ],
       [102.        ],
       [ 98.        ],
       [100.91549296],
       [100.        ],
       [104.        ],
       [100.        ],
       [ 98.        ],
       [100.        ],
       [100.91549296],
       [101.        ],
       [103.        ],
       [ 98.        ],
       [102.        ],
       [101.        ],
       [100.91549296],
       [100.91549296],
       [104.        ],
       [103.        ],
       [102.        ],
       [104.        ],
       [101.        ],
       [ 98.        ],
       [102.        ],
       [ 98.        ],
       [100.        ],
       [100.91549296],
       [103.        ],
       [104.        ],
       [ 99

In [90]:
X_train_fever.shape

(80, 1)

In [91]:
from sklearn.preprocessing import OrdinalEncoder

In [92]:
# now we have to do the "ordinal encoding" of "cough" data

oe= OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough= oe.fit_transform(X_train[['cough']])
 
# also for test dta

X_test_cough = oe.fit_transform(X_test[['cough']])

In [93]:
X_train_cough

array([[0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],

In [94]:
X_train_cough.shape

(80, 1)

In [95]:
from sklearn.preprocessing import OneHotEncoder

In [96]:
# Now we have to do "One Hot Encoding" of data "Gender" & "City"

ohe= OneHotEncoder(drop='first', sparse_output=False)

X_train_gender_city= ohe.fit_transform(X_train[['gender','city']])

X_test_gender_city = ohe.transform(X_test[['gender','city']])

In [97]:
X_train_gender_city

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 0., 1.],
       [1., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [1., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],


In [98]:
X_train_gender_city.shape

(80, 4)

In [99]:
# Extracting age
X_train_age = X_train.drop(columns=['gender','fever','cough','city']).values

# also the test data
X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values

In [100]:
X_train_age.shape

(80, 1)

In [101]:
X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis=1)
# also the test data
X_test_transformed = np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis=1)

X_train_transformed.shape

(80, 7)

# Best Way to do

In [102]:
from sklearn.compose import ColumnTransformer

In [103]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
],remainder='passthrough')

In [104]:
X_train_new=transformer.fit_transform(X_train)

In [105]:
X_train_new.shape

(80, 7)

In [106]:
df

age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [107]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [115]:
 si = SimpleImputer()
# X_train_fever= si.fit_transform(X_train[['fever']])


# # also fill test data of fever column

# X_test_fever=si.fit_transform(X_test[['fever']])

feverr=(si.fit_transform(df[['fever']]))

In [116]:
feverr

array([[103.        ],
       [100.        ],
       [101.        ],
       [ 98.        ],
       [101.        ],
       [100.84444444],
       [101.        ],
       [100.84444444],
       [100.        ],
       [101.        ],
       [100.84444444],
       [ 98.        ],
       [ 99.        ],
       [102.        ],
       [104.        ],
       [103.        ],
       [103.        ],
       [ 98.        ],
       [ 98.        ],
       [100.84444444],
       [ 98.        ],
       [ 98.        ],
       [ 98.        ],
       [ 98.        ],
       [100.        ],
       [100.84444444],
       [100.        ],
       [102.        ],
       [104.        ],
       [100.84444444],
       [101.        ],
       [103.        ],
       [101.        ],
       [ 98.        ],
       [102.        ],
       [102.        ],
       [101.        ],
       [100.        ],
       [101.        ],
       [103.        ],
       [102.        ],
       [100.84444444],
       [100.        ],
       [ 99

In [117]:
df['fever'].isnull().sum()

10

In [122]:
df=df['fever'].replace('feverr')